name: CI
on: push
jobs:
  staticChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests
        run: npm run test
